variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "git@gitlab.com:"
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/embedded-library/infrastructure/embedded-infra-lib".insteadOf https://gitlab.com/embedded-library/infrastructure/embedded-infra-lib.git
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/embedded-library/infrastructure/hal-st".insteadOf https://gitlab.com/embedded-library/infrastructure/hal-st.git

stages:
  - lint
  - build

include:
  - local: ".gitlab/linting-formatting.yml"
  - local: ".gitlab/build.yml"
